remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Ryan's GPC Enabled Cookie Banner homepage
description: Bookmark this to keep an eye on my banner updates!
